class CitiesModel {

  List<String> egyptCities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Dakahlia",
    "Red Sea",
    "Beheira",
    "Fayoum",
    "Gharbiya",
    "Ismailia",
    "Menofia",
    "Minya",
    "Qaliubiya",
    "New Valley",
    "Suez",
    "Aswan",
    "Assiut",
    "Beni Suef",
    "Port Said",
    "Damietta",
    "Sharkia",
    "South Sinai",
    "Kafr Al sheikh",
    "Matrouh",
    "Luxor",
    "Qena",
    "North Sinai",
    "Sohag"
  ];
  List<String> cairoAreas = [
    "15 May",
    "Al Azbakeyah",
    "Al Basatin",
    "Tebin",
    "El-Khalifa",
    "El darrasa",
    "Aldarb Alahmar",
    "Zawya al-Hamra",
    "El-Zaytoun",
    "Sahel",
    "El Salam",
    "Sayeda Zeinab",
    "El Sharabeya",
    "Shorouk",
    "El Daher",
    "Ataba",
    "New Cairo",
    "El Marg",
    "Ezbet el Nakhl",
    "Matareya",
    "Maadi",
    "Maasara",
    "Mokattam",
    "Manyal",
    "Mosky",
    "Nozha",
    "Waily",
    "Bab al-Shereia",
    "Bolaq",
    "Garden City",
    "Hadayek El-Kobba",
    "Helwan",
    "Dar Al Salam",
    "Shubra",
    "Tura",
    "Abdeen",
    "Abaseya",
    "Ain Shams",
    "Nasr City",
    "New Heliopolis",
    "Masr Al Qadima",
    "Mansheya Nasir",
    "Badr City",
    "Obour City",
    "Cairo Downtown",
    "Zamalek",
    "Kasr El Nile",
    "Rehab",
    "Katameya",
    "Madinty",
    "Rod Alfarag",
    "Sheraton",
    "El-Gamaleya",
    "10th of Ramadan City",
    "Helmeyat Alzaytoun",
    "New Nozha",
    "Capital New",
  ];
  List<String> gizaAreas = [
    "Giza",
    "Sixth of October",
    "Cheikh Zayed",
    "Hawamdiyah",
    "Al Badrasheen",
    "Saf",
    "Atfih",
    "Al Ayat",
    "Al-Bawaiti",
    "ManshiyetAl Qanater",
    "Oaseem",
    "Kerdasa",
    "Abu Nomros",
    "Kafr Ghati",
    "Manshiyet Al Bakari",
    "Dokki",
    "Agouza",
    "Haram",
    "Warraq",
    "Imbaba",
    "Boulaq Dakrour",
    "Al Wahat Al Baharia",
    "Omraneya",
    "Moneeb",
    "Bin Alsarayat",
    "Kit Kat",
    "Mohandessin",
    "Faisal",
    "Abu Rawash",
    "Hadayek Alahram",
    "Haraneya",
    "Hadayek October",
    "Saft Allaban",
    "Smart Village",
    "Ard Ellwaa",
  ];
  List<String> alexandriaAreas = [
    "Abu Qir",
    "Al Ibrahimeyah",
    "Azarita",
    "Anfoushi",
    "Dekheila",
    "El Soyof",
    "Ameria",
    "El Labban",
    "Al Mafrouza",
    "El Montaza",
    "Mansheya",
    "Naseria",
    "Ambrozo",
    "Bab Sharq",
    "Bourj Alarab",
    "Stanley",
    "Smouha",
    "Sidi Bishr",
    "Shads",
    "Gheet Alenab",
    "Fleming",
    "Victoria",
    "Camp Shizar",
    "Karmooz",
    "Mahta Alraml",
    "Mina El-Basal",
    "Asafra",
    "Agamy",
    "Bakos",
    "Boulkly",
    "Cleopatra",
    "Glim",
    "Al Mamurah",
    "Al Mandara",
    "Moharam Bek",
    "Elshatby",
    "Sidi Gaber",
    "North Coast/sahel",
    "Alhadra",
    "Alattarin",
    "Sidi Kerir",
    "Elgomrok",
    "Al Max",
    "Marina",
  ];
  List<String> dakahliaAreas = [
    "Mansoura",
    "Talkha",
    "Mitt Ghamr",
    "Dekernes",
    "Aga",
    "Menia El Nasr",
    "Sinbillawin",
    "El Kurdi",
    "Bani Ubaid",
    "Al Manzala",
    "tami al'amdid",
    "aljamalia",
    "Sherbin",
    "Mataria",
    "Belqas",
    "Meet Salsil",
    "Gamasa",
    "Mahalat Damana",
    "Nabroh",
  ];
  List<String> redseaAreas = [
    "Hurghada",
    "Ras Ghareb",
    "Safaga",
    "El Qusiar",
    "Marsa Alam",
    "Shalatin",
    "Halaib",
    "Aldahar",
  ];
  List<String> beheiraAreas = [
    "Damanhour",
    "Kafr El Dawar",
    "Rashid",
    "Edco",
    "Abu al-Matamir",
    "Abu Homs",
    "Delengat",
    "Mahmoudiyah",
    "Rahmaniyah",
    "Itai Baroud",
    "Housh Eissa",
    "Shubrakhit",
    "Kom Hamada",
    "Badr",
    "Wadi Natrun",
    "New Nubaria",
    "Alnoubareya",
  ];
  List<String> fayoumAreas = [
    "Fayoum",
    "Fayoum El Gedida",
    "Tamiya",
    "Snores",
    "Etsa",
    "Epschway",
    "Yusuf El Sediaq",
    "Hadqa",
    "Atsa",
    "Algamaa",
    "Sayala",
  ];
  List<String> gharbiyaAreas = [
    "Tanta",
    "Al Mahalla Al Kobra",
    "Kafr El Zayat",
    "Zefta",
    "El Santa",
    "Qutour",
    "Basion",
    "Samannoud",
  ];
  List<String> ismailiaAreas = [
    "Ismailia",
    "Fayed",
    "Qantara Sharq",
    "Qantara Gharb",
    "El Tal El Kabier",
    "Abu Sawir",
    "Kasasien El Gedida",
    "Nefesha",
    "Sheikh Zayed",
  ];
  List<String> menofiaAreas = [
    "Shbeen El Koom",
    "Sadat City",
    "Menouf",
    "Sars El-Layan",
    "Ashmon",
    "Al Bagor",
    "Quesna",
    "Berkat El Saba",
    "Tala",
    "Al Shohada",
  ];
  List<String> minyaAreas = [
    "Minya",
    "Minya El Gedida",
    "El Adwa",
    "Magagha",
    "Bani Mazar",
    "Mattay",
    "Samalut",
    "Madinat El Fekria",
    "Meloy",
    "Deir Mawas",
    "Abu Qurqas",
    "Ard Sultan",
  ];
  List<String> qaliubiyaAreas = [
    "Banha",
    "Qalyub",
    "Shubra Al Khaimah",
    "Al Qanater Charity",
    "Khanka",
    "Kafr Shukr",
    "Tukh",
    "Qaha",
    "Obour",
    "Khosous",
    "Shibin Al Qanater",
    "Mostorod",
  ];
  List<String> newValleyAreas = [
    "El Kharga",
    "Paris",
    "Mout",
    "Farafra",
    "Balat",
    "Dakhla",
  ];
  List<String> suezAreas = [
    "Suez",
    "Alganayen",
    "Ataqah",
    "Ain Sokhna",
    "Faysal",
  ];
  List<String> aswanAreas = [
    "Aswan",
    "Aswan El Gedida",
    "Drau",
    "Kom Ombo",
    "Nasr Al Nuba",
    "Kalabsha",
    "Edfu",
    "Al-Radisiyah",
    "Al Basilia",
    "Al Sibaeia",
    "Abo Simbl Al Siyahia",
    "Marsa Alam",
  ];
  List<String> assiutAreas = [
    "Assiut",
    "Assiut El Gedida",
    "Dayrout",
    "Manfalut",
    "Qusiya",
    "Abnoub",
    "Abu Tig",
    "El Ghanaim",
    "Sahel Selim",
    "El Badari",
    "Sidfa",
  ];
  List<String> beniSuefAreas = [
    "Bani Sweif",
    "Beni Suef El Gedida",
    "Al Wasta",
    "Naser",
    "Ehnasia",
    "beba",
    "Fashn",
    "Somasta",
    "Alabbaseri",
    "Mokbel",
  ];
  List<String> portSaidAreas = [
    "PorSaid",
    "Port Fouad",
    "Alarab",
    "Zohour",
    "Alsharq",
    "Aldawahi",
    "Almanakh",
    "Mubarak",
  ];
  List<String> damiettaAreas = [
    "Damietta",
    "New Damietta",
    "Ras El Bar",
    "Faraskour",
    "Zarqa",
    "alsaru",
    "alruwda",
    "Kafr El-Batikh",
    "Azbet Al Burg",
    "Meet Abou Ghalib",
    "Kafr Saad",
  ];
  List<String> sharqiaAreas = [
    "Zagazig",
    "Al Ashr Men Ramadan",
    "Minya Al Qamh",
    "Belbeis",
    "Mashtoul El Souq",
    "Qenaiat",
    "Abu Hammad",
    "El Qurain",
    "Hehia",
    "Abu Kabir",
    "Faccus",
    "El Salihia El Gedida",
    "Al Ibrahimiyah",
    "Deirb Negm",
    "Kafr Saqr",
    "Awlad Saqr",
    "Husseiniya",
    "san alhajar alqablia",
    "Manshayat Abu Omar",
  ];
  List<String> southSinaiAreas = [
    "Al Toor",
    "Sharm El-Shaikh",
    "Dahab",
    "Nuweiba",
    "Taba",
    "Saint Catherine",
    "Abu Redis",
    "Abu Zenaima",
    "Ras Sidr",
  ];
  List<String> kafrElSheikhAreas = [
    "Kafr El Sheikh",
    "Kafr El Sheikh Downtown",
    "Desouq",
    "Fooh",
    "Metobas",
    "Burg Al Burullus",
    "Baltim",
    "Masief Baltim",
    "Hamol",
    "Bella",
    "Riyadh",
    "Sidi Salm",
    "Qellen",
    "Sidi Ghazi",
  ];
  List<String> marsaMatrouhAreas = [
    "Marsa Matrouh",
    "El Hamam",
    "Alamein",
    "Dabaa",
    "Al-Nagila",
    "Sidi Brani",
    "Salloum",
    "Siwa",
    "Marina",
    "North Coast",
  ];
  List<String> luxorAreas = [
    "Luxor",
    "New Luxor",
    "Esna",
    "New Tiba",
    "Al ziynia",
    "Al Bayadieh",
    "Al Qarna",
    "Armant",
    "Al Tud",
  ];
  List<String> qenaAreas = [
    "Qena",
    "New Qena",
    "Abu Tesht",
    "Nag Hammadi",
    "Deshna",
    "Alwaqf",
    "Qaft",
    "Naqada",
    "Farshout",
    "Quos",
  ];
  List<String> northSinaiAreas = [
    "Arish",
    "Sheikh Zowaid",
    "Nakhl",
    "Rafah",
    "Bir al-Abed",
    "Al Hasana",
  ];
  List<String> sohagAreas = [
    "Sohag",
    "Sohag El Gedida",
    "Akhmeem",
    "Akhmim El Gedida",
    "Albalina",
    "El Maragha",
    "almunsha'a",
    "Dar AISalaam",
    "Gerga",
    "Jahina Al Gharbia",
    "Saqilatuh",
    "Tama",
    "Tahta",
    "Alkawthar",
  ];
}